<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Heroku</name>
   <tag></tag>
   <elementGuidId>e6a527ea-9555-43f5-b918-48e3d1af6b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Heroku')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Heroku&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Heroku&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c6f4386-dd97-440b-8d63-3108faca46c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.heroku.com</value>
      <webElementGuid>cd199138-1eb0-4d45-b81a-05d0934f1bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Heroku</value>
      <webElementGuid>920247d3-fef9-43ff-a3bf-a4b1b09c09ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Heroku</value>
      <webElementGuid>1fce31e6-7aa3-4b2f-b307-fd08a71cb0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js backgroundsize borderradius boxshadow cssanimations&quot;]/body[1]/div[@class=&quot;page-wrap gradient-primary&quot;]/div[@class=&quot;container&quot;]/h1[@class=&quot;logo&quot;]/a[1]</value>
      <webElementGuid>6b624e2b-c772-4317-bb49-4bd8bf3d13f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Heroku')]</value>
      <webElementGuid>314460f3-003b-4b84-ad54-bde1e054d922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to heroku.com'])[1]/preceding::a[1]</value>
      <webElementGuid>aa6c3e8a-d1a2-4290-8839-ffe8d18b107a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to your account'])[1]/preceding::a[2]</value>
      <webElementGuid>7abdd65b-745e-4c01-87a7-35ccf940ddd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Heroku']/parent::*</value>
      <webElementGuid>2ddf9055-582f-4469-95bb-cf0b6488d727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.heroku.com')]</value>
      <webElementGuid>82bd47d7-7d23-4ef5-8512-ee492334a05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>b61b36c5-953e-4e38-a9f4-3bfad70794b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.heroku.com' and @title = 'Heroku' and (text() = 'Heroku' or . = 'Heroku')]</value>
      <webElementGuid>573d7699-19ba-474b-83af-e878f628e1a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
